-- ============================================================
-- Employee Salary Management System
-- Database Tables
-- ============================================================


-- ============================================================
-- EMPLOYEES
-- Stores employee information and current salary details.
-- ============================================================

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name  VARCHAR2(50) NOT NULL,
    last_name   VARCHAR2(50) NOT NULL,
    salary      NUMBER NOT NULL,
    department  VARCHAR2(50),
    hire_date   DATE DEFAULT SYSDATE,

    CONSTRAINT pk_employees
        PRIMARY KEY (employee_id),

    CONSTRAINT chk_salary_positive
        CHECK (salary >= 0)
);


-- ============================================================
-- SALARY_HISTORY
-- Stores an audit trail whenever an employee's salary changes.
-- ============================================================

CREATE TABLE salary_history (
    history_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER,
    old_salary  NUMBER,
    new_salary  NUMBER,
    change_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_salary_history
        PRIMARY KEY (history_id),

    CONSTRAINT fk_sal_hist_emp
        FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id)
);


-- ============================================================
-- APP_USERS
-- Stores accounts used by the application's custom
-- authentication scheme.
-- ============================================================

CREATE TABLE app_users (
    user_id       NUMBER GENERATED ALWAYS AS IDENTITY,
    email         VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role          VARCHAR2(50) DEFAULT 'USER',
    created_at    DATE DEFAULT SYSDATE,

    CONSTRAINT pk_app_users
        PRIMARY KEY (user_id),

    CONSTRAINT uq_app_users_email
        UNIQUE (email)
);


-- ============================================================
-- ERROR_LOG
-- Stores errors captured by the application's PL/SQL
-- error-logging procedure.
-- ============================================================

CREATE TABLE error_log (
    error_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    error_message VARCHAR2(4000),
    error_date    DATE,
    module        VARCHAR2(100),
    error_code    NUMBER,
    user_name     VARCHAR2(100),

    CONSTRAINT pk_error_id
        PRIMARY KEY (error_id)
);